In [1]:
import numpy as np

print("===== NumPy Vector Calculations =====")

# Create vectors
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print("\nVector A:", A)
print("Vector B:", B)

# Addition
print("\nVector Addition:")
print(A + B)

# Subtraction
print("\nVector Subtraction:")
print(A - B)

# Dot Product
print("\nDot Product:")
print(np.dot(A, B))

# Matrix Creation
M1 = np.array([[1, 2],
               [3, 4]])

M2 = np.array([[5, 6],
               [7, 8]])

print("\nMatrix M1:")
print(M1)

print("\nMatrix M2:")
print(M2)

# Matrix Multiplication
print("\nMatrix Multiplication:")
print(np.matmul(M1, M2))

# Matrix Transpose
print("\nTranspose of M1:")
print(M1.T)

# Identity Matrix
print("\nIdentity Matrix:")
print(np.eye(3))

# Inverse Matrix
print("\nInverse of M1:")
print(np.linalg.inv(M1))

# Determinant
print("\nDeterminant of M1:")
print(np.linalg.det(M1))

# Eigenvalues and Eigenvectors
values, vectors = np.linalg.eig(M1)

print("\nEigenvalues:")
print(values)

print("\nEigenvectors:")
print(vectors)

===== NumPy Vector Calculations =====

Vector A: [1 2 3]
Vector B: [4 5 6]

Vector Addition:
[5 7 9]

Vector Subtraction:
[-3 -3 -3]

Dot Product:
32

Matrix M1:
[[1 2]
 [3 4]]

Matrix M2:
[[5 6]
 [7 8]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of M1:
[[1 3]
 [2 4]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Inverse of M1:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of M1:
-2.0000000000000004

Eigenvalues:
[-0.37228132+0.j  5.37228132+0.j]

Eigenvectors:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]
